{% set name = "Pebble" %}
{% set version = "4.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26fdcc0f36d93d8e07559d36b942b7800c6b9622626d5b587ab1a74820d02732

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - pebble
    - pebble.concurrent
    - pebble.pool

about:
  home: https://pebble.readthedocs.io/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: Pebble provides a neat API to manage threads and processes within an application.
  dev_url: https://github.com/noxdafox/pebble

extra:
  recipe-maintainers:
    - hoechenberger
