{% set name = "Pebble" %}
{% set version = "4.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a71c11fc51a620e542d017a264764045c497f1f26e571d6e9de2d16b5135c54d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - pebble
    - pebble.concurrent
    - pebble.pool

about:
  home: https://pebble.readthedocs.io/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Pebble provides a neat API to manage threads and processes within an application.
  dev_url: https://github.com/noxdafox/pebble

extra:
  recipe-maintainers:
    - hoechenberger
